name: Verificar build Docker

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Docker
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen Docker
        run: docker build -t myapp:latest .